version: '3.8'
services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/var/www/html:delegated
    ports:
      - '8001:80'
    hostname: lara.local
    domainname: local
  front:
    build:
      context: ./front
    ports:
      - '80:80'
